config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'

  get 'static_pages/products'

  get 'static_pages/contact'

  root 'static_pages#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def welcome
    render text: "Milanowski - wkłady i znicze"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def products
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>O nas</h1>
<header>Milanowski - znicze i wkłady</header>
<p>Tu będzie krótka historia firmy</p>
<%= link_to "Nasze produkty", static_pages_products_path %>
<%= link_to "Kontakt", static_pages_contact_path %>

app/views/static_pages/contact.html.erb
<h1>Kontakt</h1>
<p>Na tej stronie będą dane kontaktowe</p>
<%= link_to "Nasze produkty", static_pages_about_path %>
<%= link_to "Kontakt", static_pages_products_path %>

app/views/static_pages/products.html.erb
<h1>Nasze produkty</h1>
<p>Tutaj będzie lista naszych produktów</p>
<%= link_to "O nas", static_pages_about_path %>
<%= link_to "Kontakt", static_pages_contact_path %>